select
    id,
    to_timestamp(date_stolen) as date_stolen,
    stolen_coordinates_lat as latitude,
    stolen_coordinates_lon as longitude,
    ST_SetSRID(ST_MakePoint(stolen_coordinates_lon, stolen_coordinates_lat), 4326) as geom,
    stolen_location,
    theft_description,
    locking_description,
    lock_defeat_description,
    police_report_number,
    police_report_department,
    status,
    title,
    description,
    serial,
    manufacturer_name,
    frame_model,
    frame_colors,
    year,
    stolen,
    thumb,
    url,
    propulsion_type_slug,
    cycle_type_slug,
    registration_created_at,
    registration_updated_at,
    manufacturer_id,
    paint_description,
    frame_size,
    frame_material_slug,
    handlebar_type_slug,
    front_gear_type_slug,
    rear_gear_type_slug,
    rear_wheel_size_iso_bsd,
    front_wheel_size_iso_bsd,
    rear_tire_narrow,
    front_tire_narrow,
    extra_registration_number,
    additional_registration,
    components,
    public_images,
    ingested_at,
    record_hash,
    valid_from
from {{ source('raw_data', 'bikeindex_chicago_stolen_bikes') }}
where
    valid_to is null
    and stolen_coordinates_lon between -88 and -87.5
    and stolen_coordinates_lat between 41.62 and 42.05
