# # # """
# # # Static dictionary mapping common Census Bureau label tokens to short abbreviations.

# # # Used by CensusVariableMapper to compress variable labels into column names
# # # that fit within PostgreSQL's 63-character identifier limit.

# # # To decode an abbreviated column name, find the abbreviation in the values
# # # of ABBREVIATIONS and read back the full token from the corresponding key.

# # # Extend this dictionary as you encounter new Census domains. Keys are
# # # case-insensitive during lookup (the mapper lowercases before matching).
# # # """

# # # # fmt: off
# # # ABBREVIATIONS: dict[str, str] = {
# # #     # --- General / structural ---
# # #     "estimate":                "est",
# # #     "margin":                  "mrgn",
# # #     "error":                   "err",
# # #     "total":                   "tot",
# # #     "percent":                 "pct",
# # #     "percentage":              "pct",
# # #     "median":                  "med",
# # #     "aggregate":               "agg",
# # #     "average":                 "avg",
# # #     "number":                  "num",
# # #     "population":              "pop",
# # #     "civilian":                "civ",
# # #     "employed":                "emp",
# # #     "unemployed":              "unemp",
# # #     "income":                  "inc",
# # #     "earnings":                "earn",
# # #     "poverty":                 "pov",

# # #     # --- Demographics ---
# # #     "female":                  "f",
# # #     "male":                    "m",
# # #     "years":                   "yr",
# # #     "under":                   "un",
# # #     "over":                    "ov",
# # #     "white":                   "wht",
# # #     "black":                   "blk",
# # #     "african":                 "afr",
# # #     "american":                "amer",
# # #     "asian":                   "asn",
# # #     "hispanic":                "hisp",
# # #     "latino":                  "lat",
# # #     "native":                  "nat",
# # #     "hawaiian":                "haw",
# # #     "pacific":                 "pac",
# # #     "islander":                "isl",
# # #     "indian":                  "ind",
# # #     "alaska":                  "ak",
# # #     "alone":                   "aln",
# # #     "combination":             "comb",
# # #     "citizen":                 "ctzn",
# # #     "citizenship":             "ctzn",
# # #     "naturalized":             "ntrl",
# # #     "foreign":                 "frgn",
# # #     "born":                    "brn",

# # #     # --- Geography ---
# # #     "residence":               "res",
# # #     "metropolitan":            "metro",
# # #     "micropolitan":            "micro",
# # #     "statistical":             "stat",
# # #     "principal":               "princ",
# # #     "outside":                 "out",
# # #     "inside":                  "in",
# # #     "urbanized":               "urb",
# # #     "urban":                   "urb",
# # #     "rural":                   "rrl",
# # #     "central":                 "cntrl",
# # #     "county":                  "cnty",
# # #     "place":                   "plc",

# # #     # --- Occupation ---
# # #     "occupation":              "occ",
# # #     "occupations":             "occ",
# # #     "management":              "mgmt",
# # #     "business":                "bus",
# # #     "science":                 "sci",
# # #     "arts":                    "arts",
# # #     "financial":               "fin",
# # #     "computer":                "comp",
# # #     "engineering":             "eng",
# # #     "mathematical":            "math",
# # #     "operations":              "ops",
# # #     "production":              "prod",
# # #     "transportation":          "transp",
# # #     "material":                "matrl",
# # #     "moving":                  "mov",
# # #     "construction":            "constr",
# # #     "extraction":              "extr",
# # #     "installation":            "instl",
# # #     "maintenance":             "maint",
# # #     "repair":                  "repr",
# # #     "service":                 "svc",
# # #     "services":                "svc",
# # #     "professional":            "prof",
# # #     "protective":              "prot",
# # #     "education":               "edu",
# # #     "educational":             "edu",
# # #     "training":                "trn",
# # #     "library":                 "lib",
# # #     "healthcare":              "hlth",
# # #     "health":                  "hlth",
# # #     "care":                    "cre",
# # #     "support":                 "supp",
# # #     "practitioner":            "pract",
# # #     "practitioners":           "pract",
# # #     "technical":               "tech",
# # #     "architecture":            "arch",
# # #     "community":               "comm",
# # #     "social":                  "soc",
# # #     "legal":                   "lgl",
# # #     "building":                "bldg",
# # #     "grounds":                 "grnds",
# # #     "cleaning":                "cln",
# # #     "preparation":             "prep",
# # #     "serving":                 "srvg",
# # #     "related":                 "rel",
# # #     "personal":                "pers",
# # #     "sales":                   "sls",
# # #     "office":                  "ofc",
# # #     "administrative":          "admin",
# # #     "natural":                 "nat",
# # #     "resources":               "rsrc",
# # #     "farming":                 "farm",
# # #     "fishing":                 "fish",
# # #     "forestry":                "frst",

# # #     # --- Housing ---
# # #     "housing":                 "hous",
# # #     "units":                   "units",
# # #     "household":               "hh",
# # #     "households":              "hh",
# # #     "owner":                   "own",
# # #     "renter":                  "rnt",
# # #     "occupied":                "occ",
# # #     "vacant":                  "vac",
# # #     "tenure":                  "tnr",
# # #     "mortgage":                "mtg",
# # #     "rent":                    "rnt",
# # #     "rooms":                   "rms",
# # #     "bedrooms":                "bdrms",
# # #     "vehicles":                "veh",
# # #     "vehicle":                 "veh",
# # #     "available":               "avail",
# # #     "selected":                "sel",
# # #     "conditions":              "cond",
# # #     "monthly":                 "mo",
# # #     "costs":                   "cst",
# # #     "value":                   "val",
# # #     "structure":               "strct",

# # #     # --- Internet / technology ---
# # #     "internet":                "inet",
# # #     "subscription":            "sub",
# # #     "subscriptions":           "sub",
# # #     "broadband":               "bband",
# # #     "computer":                "comp",
# # #     "computing":               "comp",
# # #     "device":                  "dev",
# # #     "devices":                 "dev",
# # #     "type":                    "typ",

# # #     # --- Commuting / transportation ---
# # #     "commuting":               "cmtg",
# # #     "means":                   "mns",
# # #     "workers":                 "wrkrs",
# # #     "worker":                  "wrkr",
# # #     "drove":                   "drv",
# # #     "carpooled":               "crpl",
# # #     "public":                  "pub",
# # #     "transit":                 "trns",
# # #     "walked":                  "wlk",
# # #     "bicycle":                 "bike",
# # #     "taxicab":                 "taxi",
# # #     "motorcycle":              "moto",
# # #     "worked":                  "wrkd",
# # #     "home":                    "hm",
# # #     "travel":                  "trvl",
# # #     "time":                    "tm",
# # #     "departure":               "dep",
# # #     "minutes":                 "min",
# # #     "arrival":                 "arr",

# # #     # --- Other common tokens ---
# # #     "including":               "incl",
# # #     "excluding":               "excl",
# # #     "without":                 "wo",
# # #     "with":                    "w",
# # #     "children":                "chld",
# # #     "families":                "fam",
# # #     "family":                  "fam",
# # #     "people":                  "ppl",
# # #     "persons":                 "prsn",
# # #     "level":                   "lvl",
# # #     "status":                  "stat",
# # #     "attainment":              "attn",
# # #     "insurance":               "ins",
# # #     "coverage":                "cov",
# # #     "disability":              "disab",
# # #     "language":                "lang",
# # #     "spoken":                  "spkn",
# # #     "english":                 "eng",
# # #     "ability":                 "abil",
# # #     "speak":                   "spk",
# # #     "bachelor's":              "bach",
# # #     "graduate":                "grad",
# # #     "degree":                  "deg",
# # #     "school":                  "schl",
# # #     "college":                 "clg",
# # #     "enrolled":                "enrl",
# # #     "not":                     "not",
# # #     "some":                    "some",
# # #     "other":                   "oth",
# # #     "two":                     "2",
# # #     "more":                    "more",
# # #     "less":                    "less",
# # #     "than":                    "than",
# # #     "or":                      "or",
# # #     "and":                     "and",
# # #     "the":                     "",
# # #     "in":                      "in",
# # #     "of":                      "",
# # #     "to":                      "to",
# # #     "for":                     "for",
# # #     "by":                      "by",
# # #     "no":                      "no",
# # #     "all":                     "all",
# # # }
# # # # fmt: on


# # """
# # Static dictionary mapping common Census Bureau label tokens to short abbreviations.

# # Used by CensusVariableMapper to compress variable labels into column names
# # that fit within PostgreSQL's 63-character identifier limit.

# # To decode an abbreviated column name, find the abbreviation in the values
# # of ABBREVIATIONS and read back the full token from the corresponding key.

# # Extend this dictionary as you encounter new Census domains. Keys are
# # case-insensitive during lookup (the mapper lowercases before matching).
# # """

# # # fmt: off
# # ABBREVIATIONS: dict[str, str] = {
# #     # --- General / structural ---
# #     "estimate":                "est",
# #     "margin":                  "mrgn",
# #     "error":                   "err",
# #     "annotation":              "ann",
# #     "total":                   "tot",
# #     "percent":                 "pct",
# #     "percentage":              "pct",
# #     "median":                  "med",
# #     "aggregate":               "agg",
# #     "average":                 "avg",
# #     "number":                  "num",
# #     "characteristics":         "chars",

# #     # --- Demographics ---
# #     "population":              "pop",
# #     "civilian":                "civ",
# #     "female":                  "f",
# #     "male":                    "m",
# #     "years":                   "yr",
# #     "year":                    "yr",
# #     "under":                   "un",
# #     "over":                    "ov",
# #     "white":                   "wht",
# #     "black":                   "blk",
# #     "african":                 "afr",
# #     "american":                "amer",
# #     "asian":                   "asn",
# #     "hispanic":                "hisp",
# #     "latino":                  "lat",
# #     "native":                  "nat",
# #     "hawaiian":                "haw",
# #     "pacific":                 "pac",
# #     "islander":                "isl",
# #     "indian":                  "ind",
# #     "alaska":                  "ak",
# #     "alone":                   "aln",
# #     "combination":             "comb",
# #     "citizen":                 "ctzn",
# #     "citizenship":             "ctzn",
# #     "naturalized":             "ntrl",
# #     "foreign":                 "frgn",
# #     "born":                    "brn",

# #     # --- Geography ---
# #     "residence":               "res",
# #     "metropolitan":            "metro",
# #     "micropolitan":            "micro",
# #     "statistical":             "stat",
# #     "principal":               "princ",
# #     "outside":                 "out",
# #     "inside":                  "in",
# #     "urbanized":               "urb",
# #     "urban":                   "urb",
# #     "rural":                   "rrl",
# #     "central":                 "cntrl",
# #     "county":                  "cnty",
# #     "place":                   "plc",

# #     # --- Employment / occupation ---
# #     "employed":                "emp",
# #     "unemployed":              "unemp",
# #     "income":                  "inc",
# #     "earnings":                "earn",
# #     "poverty":                 "pov",
# #     "occupation":              "occ",
# #     "occupations":             "occ",
# #     "management":              "mgmt",
# #     "business":                "bus",
# #     "science":                 "sci",
# #     "arts":                    "arts",
# #     "financial":               "fin",
# #     "operations":              "ops",
# #     "computer":                "comp",
# #     "computing":               "comp",
# #     "engineering":             "eng",
# #     "mathematical":            "math",
# #     "production":              "prod",
# #     "transportation":          "transp",
# #     "material":                "matrl",
# #     "moving":                  "mov",
# #     "construction":            "constr",
# #     "extraction":              "extr",
# #     "installation":            "instl",
# #     "maintenance":             "maint",
# #     "repair":                  "repr",
# #     "service":                 "svc",
# #     "services":                "svc",
# #     "professional":            "prof",
# #     "protective":              "prot",
# #     "education":               "edu",
# #     "educational":             "edu",
# #     "training":                "trn",
# #     "library":                 "lib",
# #     "healthcare":              "hlth",
# #     "health":                  "hlth",
# #     "care":                    "cre",
# #     "support":                 "supp",
# #     "practitioner":            "pract",
# #     "practitioners":           "pract",
# #     "technical":               "tech",
# #     "architecture":            "arch",
# #     "community":               "comm",
# #     "social":                  "soc",
# #     "legal":                   "lgl",
# #     "building":                "bldg",
# #     "grounds":                 "grnds",
# #     "cleaning":                "cln",
# #     "preparation":             "prep",
# #     "serving":                 "srvg",
# #     "related":                 "rel",
# #     "personal":                "pers",
# #     "sales":                   "sls",
# #     "office":                  "ofc",
# #     "administrative":          "admin",
# #     "natural":                 "nat",
# #     "resources":               "rsrc",
# #     "farming":                 "farm",
# #     "fishing":                 "fish",
# #     "forestry":                "frst",
# #     "workers":                 "wrkrs",
# #     "worker":                  "wrkr",

# #     # --- Housing ---
# #     "physical":                "phys",
# #     "housing":                 "hous",
# #     "units":                   "units",
# #     "unit":                    "unit",
# #     "household":               "hh",
# #     "households":              "hh",
# #     "owner":                   "own",
# #     "renter":                  "rnt",
# #     "occupied":                "occ",
# #     "vacant":                  "vac",
# #     "tenure":                  "tnr",
# #     "mortgage":                "mtg",
# #     "rent":                    "rnt",
# #     "rooms":                   "rms",
# #     "room":                    "rm",
# #     "bedrooms":                "bdrms",
# #     "bedroom":                 "bdrm",
# #     "vehicles":                "veh",
# #     "vehicle":                 "veh",
# #     "available":               "avail",
# #     "selected":                "sel",
# #     "conditions":              "cond",
# #     "monthly":                 "mo",
# #     "costs":                   "cst",
# #     "value":                   "val",
# #     "structure":               "struc",
# #     "structures":              "struc",
# #     "built":                   "blt",
# #     "heating":                 "heat",
# #     "fuel":                    "fuel",
# #     "utility":                 "util",
# #     "telephone":               "tel",
# #     "plumbing":                "plmb",
# #     "kitchen":                 "ktchn",
# #     "facilities":              "fac",

# #     # --- Internet / technology ---
# #     "internet":                "inet",
# #     "subscription":            "sub",
# #     "subscriptions":           "sub",
# #     "broadband":               "bband",
# #     "device":                  "dev",
# #     "devices":                 "dev",
# #     "type":                    "typ",

# #     # --- Commuting / transportation ---
# #     "commuting":               "cmtg",
# #     "means":                   "mns",
# #     "drove":                   "drv",
# #     "carpooled":               "crpl",
# #     "public":                  "pub",
# #     "transit":                 "trns",
# #     "walked":                  "wlk",
# #     "bicycle":                 "bike",
# #     "taxicab":                 "taxi",
# #     "motorcycle":              "moto",
# #     "worked":                  "wrkd",
# #     "home":                    "hm",
# #     "travel":                  "trvl",
# #     "time":                    "tm",
# #     "departure":               "dep",
# #     "minutes":                 "min",
# #     "arrival":                 "arr",

# #     # --- Other common tokens ---
# #     "including":               "incl",
# #     "excluding":               "excl",
# #     "without":                 "wo",
# #     "with":                    "w",
# #     "children":                "chld",
# #     "families":                "fam",
# #     "family":                  "fam",
# #     "people":                  "ppl",
# #     "persons":                 "prsn",
# #     "level":                   "lvl",
# #     "status":                  "stat",
# #     "attainment":              "attn",
# #     "insurance":               "ins",
# #     "coverage":                "cov",
# #     "disability":              "disab",
# #     "language":                "lang",
# #     "spoken":                  "spkn",
# #     "english":                 "eng",
# #     "ability":                 "abil",
# #     "speak":                   "spk",
# #     "bachelor's":              "bach",
# #     "graduate":                "grad",
# #     "degree":                  "deg",
# #     "school":                  "schl",
# #     "college":                 "clg",
# #     "enrolled":                "enrl",
# #     "earlier":                 "elr",
# #     "later":                   "ltr",
# #     "not":                     "not",
# #     "some":                    "some",
# #     "other":                   "oth",
# #     "two":                     "2",
# #     "more":                    "more",
# #     "less":                    "less",
# #     "than":                    "than",
# #     "or":                      "or",
# #     "and":                     "and",
# #     "the":                     "",
# #     "in":                      "in",
# #     "of":                      "",
# #     "to":                      "to",
# #     "for":                     "for",
# #     "by":                      "by",
# #     "no":                      "no",
# #     "all":                     "all",
# #     "sex":                     "sex",
# #     "age":                     "age",
# #     "race":                    "race",
# # }
# # # fmt: on


# """
# Static dictionary mapping common Census Bureau label tokens to short abbreviations.

# Used by CensusVariableMapper to compress variable labels into column names
# that fit within PostgreSQL's 63-character identifier limit.

# To decode an abbreviated column name, find the abbreviation in the values
# of ABBREVIATIONS and read back the full token from the corresponding key.

# Extend this dictionary as you encounter new Census domains. Keys are
# case-insensitive during lookup (the mapper lowercases before matching).
# """

# # fmt: off
# ABBREVIATIONS: dict[str, str] = {
#     # --- General / structural ---
#     "estimate":                "est",
#     "margin":                  "mrgn",
#     "error":                   "err",
#     "annotation":              "ann",
#     "total":                   "tot",
#     "percent":                 "pct",
#     "percentage":              "pct",
#     "median":                  "med",
#     "aggregate":               "agg",
#     "average":                 "avg",
#     "number":                  "num",
#     "characteristics":         "chars",

#     # --- Demographics ---
#     "population":              "pop",
#     "civilian":                "civ",
#     "female":                  "f",
#     "male":                    "m",
#     "years":                   "yr",
#     "year":                    "yr",
#     "under":                   "un",
#     "over":                    "ov",
#     "white":                   "wht",
#     "black":                   "blk",
#     "african":                 "afr",
#     "american":                "amer",
#     "asian":                   "asn",
#     "hispanic":                "hisp",
#     "latino":                  "lat",
#     "native":                  "nat",
#     "hawaiian":                "haw",
#     "pacific":                 "pac",
#     "islander":                "isl",
#     "indian":                  "ind",
#     "alaska":                  "ak",
#     "alone":                   "aln",
#     "combination":             "comb",
#     "citizen":                 "ctzn",
#     "citizenship":             "ctzn",
#     "naturalized":             "ntrl",
#     "foreign":                 "frgn",
#     "born":                    "brn",

#     # --- Geography ---
#     "residence":               "res",
#     "metropolitan":            "metro",
#     "micropolitan":            "micro",
#     "statistical":             "stat",
#     "principal":               "princ",
#     "outside":                 "out",
#     "inside":                  "in",
#     "urbanized":               "urb",
#     "urban":                   "urb",
#     "rural":                   "rrl",
#     "central":                 "cntrl",
#     "county":                  "cnty",
#     "place":                   "plc",

#     # --- Employment / occupation ---
#     "employed":                "emp",
#     "unemployed":              "unemp",
#     "income":                  "inc",
#     "earnings":                "earn",
#     "poverty":                 "pov",
#     "occupation":              "occ",
#     "occupations":             "occ",
#     "management":              "mgmt",
#     "business":                "bus",
#     "science":                 "sci",
#     "arts":                    "arts",
#     "financial":               "fin",
#     "operations":              "ops",
#     "computer":                "comp",
#     "computing":               "comp",
#     "engineering":             "eng",
#     "mathematical":            "math",
#     "production":              "prod",
#     "transportation":          "transp",
#     "material":                "matrl",
#     "moving":                  "mov",
#     "construction":            "constr",
#     "extraction":              "extr",
#     "installation":            "instl",
#     "maintenance":             "maint",
#     "repair":                  "repr",
#     "service":                 "svc",
#     "services":                "svc",
#     "professional":            "prof",
#     "protective":              "prot",
#     "education":               "edu",
#     "educational":             "edu",
#     "training":                "trn",
#     "library":                 "lib",
#     "healthcare":              "hlth",
#     "health":                  "hlth",
#     "care":                    "cre",
#     "support":                 "supp",
#     "practitioner":            "pract",
#     "practitioners":           "pract",
#     "technical":               "tech",
#     "architecture":            "arch",
#     "community":               "comm",
#     "social":                  "soc",
#     "legal":                   "lgl",
#     "building":                "bldg",
#     "grounds":                 "grnds",
#     "cleaning":                "cln",
#     "preparation":             "prep",
#     "serving":                 "srvg",
#     "related":                 "rel",
#     "personal":                "pers",
#     "sales":                   "sls",
#     "office":                  "ofc",
#     "administrative":          "admin",
#     "natural":                 "nat",
#     "resources":               "rsrc",
#     "farming":                 "farm",
#     "fishing":                 "fish",
#     "forestry":                "frst",
#     "workers":                 "wrkrs",
#     "worker":                  "wrkr",

#     # --- Housing ---
#     "physical":                "phys",
#     "housing":                 "hous",
#     "units":                   "units",
#     "unit":                    "unit",
#     "household":               "hh",
#     "households":              "hh",
#     "owner":                   "own",
#     "renter":                  "rnt",
#     "occupied":                "occ",
#     "vacant":                  "vac",
#     "tenure":                  "tnr",
#     "mortgage":                "mtg",
#     "rent":                    "rnt",
#     "rooms":                   "rms",
#     "room":                    "rm",
#     "bedrooms":                "bdrms",
#     "bedroom":                 "bdrm",
#     "vehicles":                "veh",
#     "vehicle":                 "veh",
#     "available":               "avail",
#     "selected":                "sel",
#     "conditions":              "cond",
#     "monthly":                 "mo",
#     "costs":                   "cst",
#     "value":                   "val",
#     "structure":               "struc",
#     "structures":              "struc",
#     "built":                   "blt",
#     "heating":                 "heat",
#     "fuel":                    "fuel",
#     "utility":                 "util",
#     "telephone":               "tel",
#     "plumbing":                "plmb",
#     "kitchen":                 "ktchn",
#     "facilities":              "fac",

#     # --- Internet / technology ---
#     "internet":                "inet",
#     "subscription":            "sub",
#     "subscriptions":           "sub",
#     "broadband":               "bband",
#     "device":                  "dev",
#     "devices":                 "dev",
#     "type":                    "typ",

#     # --- Commuting / transportation ---
#     "commuting":               "cmtg",
#     "means":                   "mns",
#     "drove":                   "drv",
#     "carpooled":               "crpl",
#     "public":                  "pub",
#     "transit":                 "trns",
#     "walked":                  "wlk",
#     "bicycle":                 "bike",
#     "taxicab":                 "taxi",
#     "motorcycle":              "moto",
#     "worked":                  "wrkd",
#     "home":                    "hm",
#     "travel":                  "trvl",
#     "time":                    "tm",
#     "departure":               "dep",
#     "minutes":                 "min",
#     "arrival":                 "arr",

#     # --- Other common tokens ---
#     "including":               "incl",
#     "excluding":               "excl",
#     "without":                 "wo",
#     "with":                    "w",
#     "children":                "chld",
#     "families":                "fam",
#     "family":                  "fam",
#     "people":                  "ppl",
#     "persons":                 "prsn",
#     "level":                   "lvl",
#     "status":                  "stat",
#     "attainment":              "attn",
#     "insurance":               "ins",
#     "coverage":                "cov",
#     "disability":              "disab",
#     "language":                "lang",
#     "spoken":                  "spkn",
#     "english":                 "eng",
#     "ability":                 "abil",
#     "speak":                   "spk",
#     "bachelor's":              "bach",
#     "graduate":                "grad",
#     "degree":                  "deg",
#     "school":                  "schl",
#     "college":                 "clg",
#     "enrolled":                "enrl",
#     "earlier":                 "elr",
#     "later":                   "ltr",
#     "not":                     "not",
#     "some":                    "some",
#     "other":                   "oth",
#     "two":                     "2",
#     "more":                    "more",
#     "less":                    "less",
#     "than":                    "than",
#     "or":                      "or",
#     "and":                     "and",
#     "the":                     "",
#     "in":                      "in",
#     "of":                      "",
#     "to":                      "to",
#     "for":                     "for",
#     "by":                      "by",
#     "no":                      "no",
#     "all":                     "all",
#     "sex":                     "sex",
#     "age":                     "age",
#     "race":                    "race",
# }
# # fmt: on


"""
Static dictionary mapping common Census Bureau label tokens to short abbreviations.

Used by CensusVariableMapper to compress variable labels into column names
that fit within PostgreSQL's 63-character identifier limit.

To decode an abbreviated column name, find the abbreviation in the values
of ABBREVIATIONS and read back the full token from the corresponding key.

Extend this dictionary as you encounter new Census domains. Keys are
case-insensitive during lookup (the mapper lowercases before matching).
"""

# fmt: off
ABBREVIATIONS: dict[str, str] = {
    # --- General / structural ---
    "estimate":                "est",
    "margin":                  "mrgn",
    "error":                   "err",
    "annotation":              "ann",
    "total":                   "tot",
    "percent":                 "pct",
    "percentage":              "pct",
    "median":                  "med",
    "aggregate":               "agg",
    "average":                 "avg",
    "number":                  "num",
    "characteristics":         "chars",

    # --- Demographics ---
    "population":              "pop",
    "civilian":                "civ",
    "female":                  "f",
    "male":                    "m",
    "years":                   "yr",
    "year":                    "yr",
    "under":                   "un",
    "over":                    "ov",
    "white":                   "wht",
    "black":                   "blk",
    "african":                 "afr",
    "american":                "amer",
    "asian":                   "asn",
    "hispanic":                "hisp",
    "latino":                  "lat",
    "native":                  "nat",
    "hawaiian":                "haw",
    "pacific":                 "pac",
    "islander":                "isl",
    "indian":                  "ind",
    "alaska":                  "ak",
    "alone":                   "aln",
    "combination":             "comb",
    "citizen":                 "ctzn",
    "citizenship":             "ctzn",
    "naturalized":             "ntrl",
    "foreign":                 "frgn",
    "born":                    "brn",

    # --- Geography ---
    "residence":               "res",
    "metropolitan":            "metro",
    "micropolitan":            "micro",
    "statistical":             "stat",
    "principal":               "princ",
    "outside":                 "out",
    "inside":                  "in",
    "urbanized":               "urb",
    "urban":                   "urb",
    "rural":                   "rrl",
    "central":                 "cntrl",
    "county":                  "cnty",
    "place":                   "plc",

    # --- Employment / occupation ---
    "employed":                "emp",
    "unemployed":              "unemp",
    "income":                  "inc",
    "earnings":                "earn",
    "poverty":                 "pov",
    "occupation":              "occ",
    "occupations":             "occ",
    "management":              "mgmt",
    "business":                "bus",
    "science":                 "sci",
    "arts":                    "arts",
    "financial":               "fin",
    "operations":              "ops",
    "computer":                "comp",
    "computing":               "comp",
    "engineering":             "eng",
    "mathematical":            "math",
    "production":              "prod",
    "transportation":          "transpo",
    "material":                "matrl",
    "moving":                  "mov",
    "construction":            "constr",
    "extraction":              "extr",
    "installation":            "instl",
    "maintenance":             "maint",
    "repair":                  "repr",
    "service":                 "srvc",
    "services":                "srvc",
    "professional":            "prof",
    "protective":              "prot",
    "education":               "edu",
    "educational":             "edu",
    "training":                "trn",
    "library":                 "lib",
    "healthcare":              "hlth",
    "health":                  "hlth",
    "care":                    "care",
    "support":                 "supp",
    "practitioner":            "pract",
    "practitioners":           "pract",
    "technical":               "tech",
    "architecture":            "arch",
    "community":               "comm",
    "social":                  "soc",
    "legal":                   "law",
    "building":                "bldg",
    "grounds":                 "grnds",
    "cleaning":                "cln",
    "preparation":             "prep",
    "serving":                 "srvg",
    "related":                 "rel",
    "personal":                "pers",
    "sales":                   "sls",
    "office":                  "ofc",
    "administrative":          "admin",
    "natural":                 "nat",
    "resources":               "rsrc",
    "farming":                 "farm",
    "fishing":                 "fish",
    "forestry":                "frst",
    "workers":                 "wrkrs",
    "worker":                  "wrkr",

    # --- Housing ---
    "physical":                "phys",
    "housing":                 "hous",
    "units":                   "units",
    "unit":                    "unit",
    "household":               "hh",
    "households":              "hh",
    "owner":                   "own",
    "renter":                  "rnt",
    "occupied":                "occ",
    "vacant":                  "vac",
    "tenure":                  "tnr",
    "mortgage":                "mtg",
    "rent":                    "rnt",
    "rooms":                   "rms",
    "room":                    "rm",
    "bedrooms":                "bdrms",
    "bedroom":                 "bdrm",
    "vehicles":                "veh",
    "vehicle":                 "veh",
    "available":               "avail",
    "selected":                "sel",
    "conditions":              "cond",
    "monthly":                 "mo",
    "costs":                   "cst",
    "value":                   "val",
    "structure":               "struc",
    "structures":              "struc",
    "built":                   "blt",
    "heating":                 "heat",
    "fuel":                    "fuel",
    "utility":                 "util",
    "telephone":               "tel",
    "plumbing":                "plmb",
    "kitchen":                 "ktchn",
    "facilities":              "fac",

    # --- Internet / technology ---
    "internet":                "inet",
    "subscription":            "sub",
    "subscriptions":           "sub",
    "broadband":               "bband",
    "device":                  "dev",
    "devices":                 "dev",
    "type":                    "typ",

    # --- Commuting / transportation ---
    "commuting":               "cmtg",
    "means":                   "",
    "drove":                   "drv",
    "carpooled":               "crpl",
    "public":                  "pub",
    "transit":                 "trns",
    "walked":                  "wlk",
    "bicycle":                 "bike",
    "taxicab":                 "taxi",
    "motorcycle":              "moto",
    "worked":                  "wrkd",
    "home":                    "hm",
    "travel":                  "trvl",
    "time":                    "tm",
    "departure":               "dep",
    "minutes":                 "min",
    "arrival":                 "arr",

    # --- Other common tokens ---
    "including":               "incl",
    "excluding":               "excl",
    "without":                 "wo",
    "with":                    "w",
    "children":                "chld",
    "families":                "fam",
    "family":                  "fam",
    "people":                  "ppl",
    "persons":                 "prsn",
    "level":                   "lvl",
    "status":                  "stat",
    "attainment":              "attn",
    "insurance":               "ins",
    "coverage":                "cov",
    "disability":              "disab",
    "language":                "lang",
    "spoken":                  "spkn",
    "english":                 "eng",
    "ability":                 "abil",
    "speak":                   "spk",
    "bachelor's":              "bach",
    "graduate":                "grad",
    "degree":                  "deg",
    "school":                  "schl",
    "college":                 "clg",
    "enrolled":                "enrl",
    "earlier":                 "elr",
    "later":                   "ltr",
    "not":                     "not",
    "some":                    "some",
    "other":                   "oth",
    "two":                     "2",
    "more":                    "more",
    "less":                    "less",
    "than":                    "than",
    "or":                      "or",
    "and":                     "and",
    "the":                     "",
    "in":                      "in",
    "of":                      "",
    "to":                      "to",
    "for":                     "for",
    "by":                      "by",
    "no":                      "no",
    "all":                     "all",
    "sex":                     "sex",
    "age":                     "age",
    "race":                    "race",
}
# fmt: on
