with source as (
    select
        case_number::text as case_number,
        date::timestamp with time zone as date,
        block::text as block,
        victimization_primary::text as victimization_primary,
        incident_primary::text as incident_primary,
        gunshot_injury_i::text as gunshot_injury_i,
        unique_id::text as unique_id,
        zip_code::text as zip_code,
        ward::numeric as ward,
        community_area::text as community_area,
        street_outreach_organization::text as street_outreach_organization,
        area::numeric as area,
        district::numeric as district,
        beat::text as beat,
        age::text as age,
        sex::text as sex,
        race::text as race,
        victimization_fbi_cd::text as victimization_fbi_cd,
        incident_fbi_cd::text as incident_fbi_cd,
        victimization_fbi_descr::text as victimization_fbi_descr,
        incident_fbi_descr::text as incident_fbi_descr,
        victimization_iucr_cd::text as victimization_iucr_cd,
        incident_iucr_cd::text as incident_iucr_cd,
        victimization_iucr_secondary::text as victimization_iucr_secondary,
        incident_iucr_secondary::text as incident_iucr_secondary,
        homicide_victim_first_name::text as homicide_victim_first_name,
        homicide_victim_mi::text as homicide_victim_mi,
        homicide_victim_last_name::text as homicide_victim_last_name,
        month::numeric as month,
        day_of_week::numeric as day_of_week,
        hour::numeric as hour,
        location_description::text as location_description,
        state_house_district::text as state_house_district,
        state_senate_district::text as state_senate_district,
        updated::timestamp with time zone as updated,
        latitude::numeric as latitude,
        longitude::numeric as longitude,
        location::geometry(POINT, 4326) as location,
        ingested_at::timestamp with time zone as ingested_at,
        socrata_id::text as socrata_id,
        socrata_updated_at::timestamp with time zone as socrata_updated_at,
        socrata_created_at::timestamp with time zone as socrata_created_at,
        socrata_version::text as socrata_version
    from {{ source('raw_data', 'chicago_homicide_and_non_fatal_shooting_victimizations') }}
)

select
    case_number,
    date,
    block,
    victimization_primary,
    incident_primary,
    gunshot_injury_i,
    unique_id,
    zip_code,
    ward,
    community_area,
    street_outreach_organization,
    area,
    district,
    beat,
    age,
    sex,
    race,
    victimization_fbi_cd,
    incident_fbi_cd,
    victimization_fbi_descr,
    incident_fbi_descr,
    victimization_iucr_cd,
    incident_iucr_cd,
    victimization_iucr_secondary,
    incident_iucr_secondary,
    homicide_victim_first_name,
    homicide_victim_mi,
    homicide_victim_last_name,
    month,
    day_of_week,
    hour,
    location_description,
    state_house_district,
    state_senate_district,
    updated,
    latitude,
    longitude,
    location,
    ingested_at,
    socrata_id,
    socrata_updated_at,
    socrata_created_at,
    socrata_version
from source
