create table if not exists raw_data.chicago_street_center_lines (
    "fnode_id" numeric,
    "tnode_id" numeric,
    "the_geom" geometry(MultiLineString, 4326),
    "objectid" numeric,
    "trans_id" numeric,
    "pre_dir" text,
    "street_nam" text,
    "street_typ" text,
    "suf_dir" text,
    "streetname" numeric,
    "l_f_add" numeric,
    "l_t_add" numeric,
    "r_f_add" numeric,
    "r_t_add" numeric,
    "logiclf" numeric,
    "logiclt" numeric,
    "logicrf" numeric,
    "logicrt" numeric,
    "class" text,
    "status" text,
    "status_dat" timestamptz,
    "tiered" text,
    "oneway_dir" text,
    "dir_travel" text,
    "ewns" numeric,
    "l_parity" text,
    "r_parity" text,
    "f_zlev" numeric,
    "t_zlev" numeric,
    "l_fips" numeric,
    "r_fips" numeric,
    "r_zip" text,
    "l_zip" text,
    "r_censusbl" text,
    "l_censusbl" text,
    "f_cross" text,
    "f_cross_st" numeric,
    "t_cross" text,
    "t_cross_st" numeric,
    "length" numeric,
    "edit_date" numeric,
    "edit_type" text,
    "flag_strin" text,
    "ewns_dir" text,
    "ewns_coord" numeric,
    "create_use" text,
    "create_tim" timestamptz,
    "update_use" text,
    "update_tim" timestamptz,
    "shape_len" numeric,
    "ingested_at" timestamptz not null default (now() at time zone 'UTC'),
    "socrata_id" text,
    "socrata_updated_at" timestamptz,
    "socrata_created_at" timestamptz,
    "socrata_version" text,
    "record_hash" text not null,
    "valid_from" timestamptz not null default (now() at time zone 'utc'),
    "valid_to" timestamptz
);
alter table raw_data.chicago_street_center_lines
    add constraint uq_chicago_street_center_lines_entity_hash
    unique (objectid, record_hash);
create index if not exists ix_chicago_street_center_lines_current
    on raw_data.chicago_street_center_lines (objectid)
    where valid_to is null;
