create table raw_data.medicare_inpatient_by_provider_and_service (
    "rndrng_prvdr_ccn" text,
    "rndrng_prvdr_org_name" text,
    "rndrng_prvdr_city" text,
    "rndrng_prvdr_st" text,
    "rndrng_prvdr_state_fips" text,
    "rndrng_prvdr_zip5" text,
    "rndrng_prvdr_state_abrvtn" text,
    "rndrng_prvdr_ruca" text,
    "rndrng_prvdr_ruca_desc" text,
    "drg_cd" text,
    "drg_desc" text,
    "tot_dschrgs" text,
    "avg_submtd_cvrd_chrg" text,
    "avg_tot_pymt_amt" text,
    "avg_mdcr_pymt_amt" text,
    "vintage" text not null,
    "_source_modified" text,
    "ingested_at" timestamptz not null default (now() at time zone 'UTC'),
    "record_hash" text not null,
    "valid_from" timestamptz not null default (now() at time zone 'UTC'),
    "valid_to" timestamptz
);
alter table raw_data.medicare_inpatient_by_provider_and_service
    add constraint uq_medicare_inpatient_by_provider_and_service_entity_hash
    unique ("rndrng_prvdr_ccn", "drg_cd", "vintage", "record_hash");
create index ix_medicare_inpatient_by_provider_and_service_current
    on raw_data.medicare_inpatient_by_provider_and_service ("rndrng_prvdr_ccn", "drg_cd", "vintage")
    where "valid_to" is null;


create table raw_data.pdc_hospital_general_information (
    "facility_id" text,
    "facility_name" text,
    "address" text,
    "citytown" text,
    "state" text,
    "zip_code" text,
    "countyparish" text,
    "telephone_number" text,
    "hospital_type" text,
    "hospital_ownership" text,
    "emergency_services" text,
    "meets_criteria_for_birthing_friendly_designation" text,
    "hospital_overall_rating" text,
    "hospital_overall_rating_footnote" text,
    "mort_group_measure_count" text,
    "count_of_facility_mort_measures" text,
    "count_of_mort_measures_better" text,
    "count_of_mort_measures_no_different" text,
    "count_of_mort_measures_worse" text,
    "mort_group_footnote" text,
    "safety_group_measure_count" text,
    "count_of_facility_safety_measures" text,
    "count_of_safety_measures_better" text,
    "count_of_safety_measures_no_different" text,
    "count_of_safety_measures_worse" text,
    "safety_group_footnote" text,
    "readm_group_measure_count" text,
    "count_of_facility_readm_measures" text,
    "count_of_readm_measures_better" text,
    "count_of_readm_measures_no_different" text,
    "count_of_readm_measures_worse" text,
    "readm_group_footnote" text,
    "pt_exp_group_measure_count" text,
    "count_of_facility_pt_exp_measures" text,
    "pt_exp_group_footnote" text,
    "te_group_measure_count" text,
    "count_of_facility_te_measures" text,
    "te_group_footnote" text,
    "_source_dataset" text not null,
    "_source_modified" text,
    "ingested_at" timestamptz not null default (now() at time zone 'UTC'),
    "record_hash" text not null,
    "valid_from" timestamptz not null default (now() at time zone 'UTC'),
    "valid_to" timestamptz
);
alter table raw_data.pdc_hospital_general_information
    add constraint uq_pdc_hospital_general_information_entity_hash
    unique ("facility_id", "record_hash");
create index ix_pdc_hospital_general_information_current
    on raw_data.pdc_hospital_general_information ("facility_id")
    where "valid_to" is null;


create table raw_data.openpayments_general_payments (
    "change_type" text,
    "covered_recipient_type" text,
    "teaching_hospital_ccn" text,
    "teaching_hospital_id" text,
    "teaching_hospital_name" text,
    "covered_recipient_profile_id" text,
    "covered_recipient_npi" text,
    "covered_recipient_first_name" text,
    "covered_recipient_middle_name" text,
    "covered_recipient_last_name" text,
    "covered_recipient_name_suffix" text,
    "recipient_primary_business_street_address_line1" text,
    "recipient_primary_business_street_address_line2" text,
    "recipient_city" text,
    "recipient_state" text,
    "recipient_zip_code" text,
    "recipient_country" text,
    "recipient_province" text,
    "recipient_postal_code" text,
    "covered_recipient_primary_type_1" text,
    "covered_recipient_primary_type_2" text,
    "covered_recipient_primary_type_3" text,
    "covered_recipient_primary_type_4" text,
    "covered_recipient_primary_type_5" text,
    "covered_recipient_primary_type_6" text,
    "covered_recipient_specialty_1" text,
    "covered_recipient_specialty_2" text,
    "covered_recipient_specialty_3" text,
    "covered_recipient_specialty_4" text,
    "covered_recipient_specialty_5" text,
    "covered_recipient_specialty_6" text,
    "covered_recipient_license_state_code1" text,
    "covered_recipient_license_state_code2" text,
    "covered_recipient_license_state_code3" text,
    "covered_recipient_license_state_code4" text,
    "covered_recipient_license_state_code5" text,
    "submitting_applicable_manufacturer_or_applicable_gpo_name" text,
    "applicable_manufacturer_or_applicable_gpo_making_payment_id" text,
    "applicable_manufacturer_or_applicable_gpo_making_payment_name" text,
    "applicable_manufacturer_or_applicable_gpo_making_payment_state" text,
    "applicable_manufacturer_or_applicable_gpo_making_payment_countr" text,
    "total_amount_of_payment_usdollars" text,
    "date_of_payment" text,
    "number_of_payments_included_in_total_amount" text,
    "form_of_payment_or_transfer_of_value" text,
    "nature_of_payment_or_transfer_of_value" text,
    "city_of_travel" text,
    "state_of_travel" text,
    "country_of_travel" text,
    "physician_ownership_indicator" text,
    "third_party_payment_recipient_indicator" text,
    "name_of_third_party_entity_receiving_payment_or_transfer_of_ccf" text,
    "charity_indicator" text,
    "third_party_equals_covered_recipient_indicator" text,
    "contextual_information" text,
    "delay_in_publication_indicator" text,
    "record_id" text,
    "dispute_status_for_publication" text,
    "related_product_indicator" text,
    "covered_or_noncovered_indicator_1" text,
    "indicate_drug_or_biological_or_device_or_medical_supply_1" text,
    "product_category_or_therapeutic_area_1" text,
    "name_of_drug_or_biological_or_device_or_medical_supply_1" text,
    "associated_drug_or_biological_ndc_1" text,
    "associated_device_or_medical_supply_pdi_1" text,
    "covered_or_noncovered_indicator_2" text,
    "indicate_drug_or_biological_or_device_or_medical_supply_2" text,
    "product_category_or_therapeutic_area_2" text,
    "name_of_drug_or_biological_or_device_or_medical_supply_2" text,
    "associated_drug_or_biological_ndc_2" text,
    "associated_device_or_medical_supply_pdi_2" text,
    "covered_or_noncovered_indicator_3" text,
    "indicate_drug_or_biological_or_device_or_medical_supply_3" text,
    "product_category_or_therapeutic_area_3" text,
    "name_of_drug_or_biological_or_device_or_medical_supply_3" text,
    "associated_drug_or_biological_ndc_3" text,
    "associated_device_or_medical_supply_pdi_3" text,
    "covered_or_noncovered_indicator_4" text,
    "indicate_drug_or_biological_or_device_or_medical_supply_4" text,
    "product_category_or_therapeutic_area_4" text,
    "name_of_drug_or_biological_or_device_or_medical_supply_4" text,
    "associated_drug_or_biological_ndc_4" text,
    "associated_device_or_medical_supply_pdi_4" text,
    "covered_or_noncovered_indicator_5" text,
    "indicate_drug_or_biological_or_device_or_medical_supply_5" text,
    "product_category_or_therapeutic_area_5" text,
    "name_of_drug_or_biological_or_device_or_medical_supply_5" text,
    "associated_drug_or_biological_ndc_5" text,
    "associated_device_or_medical_supply_pdi_5" text,
    "program_year" text,
    "payment_publication_date" text,
    "_source_dataset" text not null,
    "_source_modified" text,
    "ingested_at" timestamptz not null default (now() at time zone 'UTC'),
    "record_hash" text not null,
    "valid_from" timestamptz not null default (now() at time zone 'UTC'),
    "valid_to" timestamptz
);
alter table raw_data.openpayments_general_payments
    add constraint uq_openpayments_general_payments_entity_hash
    unique ("record_id", "program_year", "record_hash");
create index ix_openpayments_general_payments_current
    on raw_data.openpayments_general_payments ("record_id", "program_year")
    where "valid_to" is null;

